dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3

compiler:
  solc:
    version: 0.8.20

networks:
  default: development
  sepolia:
    host: https://sepolia.infura.io/v3/9a0ad6308f4f4a9cb936060547bf7a26
    chainid: 11155111
    explorer: https://sepolia.etherscan.io
    verify: True
  mainnet-fork:
    host: http://127.0.0.1:8545
    chainid: 1


